[package]
name = "shouxtech/observers"
description = "Observers to help simplify some specific event handling"
version = "0.0.6"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
